### ISSUE TITLE
Event Analyzer

### ISSUE THREAD

**Issue by dejitarudemon** [dejitarudemon/GithubUserActivity#6]
# Requirement

it's necessary to create an Event Analyzer module that will analyze user events from Github and return a report

# Todo:

- [x] function for anlyze events
```go
func Analyze(event *Events) map[string]Events {}
```
- [x] function for fmt.print events
```go
func (events Events) String string {}
```
- [x] test the functions
